name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  check-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.4.0"
          cache: yarn

      - name: install
        run: yarn
      - name: check type
        run: yarn check-type

  build-deploy:
    runs-on: ubuntu-latest
    needs:
      - check-type
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.4.0"
          cache: yarn
      - uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-build-

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
